src.main/ElectronMain.hx
Fix for #104 bug when trying to run on MacOs due to window not being set to visible first. Simply pasted the fix from there into an actual PR. Have not tested if it breaks anything on windows just yet, but I don't think it should. Please test it out. Forgive me if I did not follow pr post guidelines as this is my first one, I am going to go take a look at them now if they exist and update this to match.
=> fix startup error when running on MacOs

.github/workflows/ubuntu.yml
Addresses #54
Hey I saw that #54 was open and figured I'd take a stab at adding an action for it based off of the discussion from there. This adds a new action to package an Ubuntu build and only exposes the AppImage. I figure for the snap we would want to have an action that actually publishes it to the Snap Store and that's why I didn't add it. See attached the AppImage running on my system.
=> Add Action for Ubuntu Build

.github/workflows/main.yml
This PR is for issue #53, see comment https://github.com/deepnight/led/pull/111#issuecomment-707339981
The DMG file should not have any of those issues outlined in the comment.
=> Make the distribution use the DMG file rather than the zip file

app/assets/css/app.scss, app/assets/tpl/editEntityDefs.html, src.data/data/DataTypes.hx, src.data/data/def/FieldDef.hx, src.data/data/inst/FieldInstance.hx, src.renderer/Lang.hx, src.renderer/exporter/Tiled.hx, src.renderer/misc/FieldTypeConverter.hx, src.renderer/ui/EntityInstanceEditor.hx, src.renderer/ui/FieldInstancesForm.hx, src.renderer/ui/modal/panel/EditEntityDefs.hx
* Added `F_File` type to properties. Acts exactly the same way as `F_String` with extra flavor of file select and extension filters.
* Redid entity instance editor a bit and implemented the stretch bar on the side, allowing user to manually resize it. Because 200 pixels is very little.
Considerations:
* Ideally F_File should validate text field to check that file exists and not an absolute path, but I'm not sure how to implement it.
* Currently stretch size is not retained, and probably should be saved in the editor config?
=> Add F_File type

doc.hxml, schema.json, src.doc/XmlDocToMarkdown.hx
Here's a somewhat messy start to a JSON schema generator. I used it to quickly generate Rust structs using `quicktype`, but it's worth noting that I wasn't completely satisfied with the generated structs and modified them manually afterwards. I'm not sure if that is because of quicktypes rust generator implementation or if it is because the JSON schema is not as strictly typed or correctly structured as it should be.
Either way, here it is if it is useful. I probably won't have time myself to clean it up much if it needs improvement, but even if it is just useful as a base for somebody who wants to do a final iteration.
Also, I manually formatted the schema.json for readability using VSCode after running the command to generate it. That may or may not be something we want to do.
=> Add JSON Schema and Schema Generator

docs/JSON_DOC.md, docs/JSON_SCHEMA.json, src/electron.renderer/data/Level.hx, src/electron.renderer/display/FieldInstanceRender.hx, src/electron.renderer/ui/FieldDefsForm.hx, src/electron.renderer/ui/FieldInstancesForm.hx
A user may want to add an array of points to an entity where the points have no directional relationship to eachother. This would make the path / star display modes unsuitable. An example of this would be a series of points in the world which an entity will investigate in a random order. This PR introduces a new `Points` display mode, which displays the point array as a series of unconnected points.
Points:
Star of points:
Path of points;
Path of points (looping):
Let me know what you think! Cheers.
=> A new point display mode for unconnected points

app/samples/Entities.ldtk
Very small change, but in this sample it seems the enum reference has an underscore as defined but the instance does not.
=> Underscore missing

src/electron.renderer/data/def/FieldDef.hx
Found an annoying crash when you set the `Regex Check` string to anything, validate, and then set it to an empty string and validate again.
That crash will happen on every entity instances of the type you messed up.
`regex` should be set to `null` but it's set to `"//g"` and causes a crash whenever you change the corresponding property on the entity.
```jsonc
"fieldDefs": [
{
"identifier": "String",
// ...
"regex": "//g", // This should be null instead
// ...
}
]
```
This simple PR should take care of that.
Steps to reproduce without the fix:
* Create a new project entity
* Add a String field
* Set regex check to anything and validate by pressing enter for example
* Set regex check to an empty string (remove every characters) and validate
* Put an instance of that entity in a level
* …
=> Fix regex not null when it's an empty string

docs/JSON_SCHEMA.json
When using LdtkIcons the field `relPath` contains a `null` which is currently not allowed in the schema.
Made relPath optional
=> Fix parsing error when using embedded atlas LdtkIcons

doc.hxml, docs/MINIMAL_JSON_SCHEMA.json, src/docGenerator/DocGenerator.hx
Generate another scheme with all internal, removed and deprecated fields removed this will produce much cleaner quicktype files that are friendlier to work with.
=> Generate a minimal Schema for quicktype

src/electron.renderer/Lang.hx
See https://www.lua.org/about.html
Like most names, it should be written in lower case with an initial capital, that is, "Lua". Please do not write it as "LUA", which is both ugly and confusing, because then it becomes an acronym with different meanings for different people. So, please, write "Lua" right!
=> Change LUA to Lua

src/electron.renderer/ui/modal/panel/EditAllAutoLayerRules.hx
Observe layer offset when rendering affected cells of an auto-layer rule.
Fixes #737
=> Fixed offset in showAffectedCells

app/assets/tpl/pages/editor.html, src/electron.common/Settings.hx, src/electron.renderer/EditorTypes.hx, src/electron.renderer/display/LayerRender.hx, src/electron.renderer/display/LevelRender.hx, src/electron.renderer/page/Editor.hx, src/electron.renderer/ui/ts/TileTagger.hx
This change adds an overlay to tileset layers to show which tiles have which enum values assigned to them. It's triggered by clicking a new "Tile enums" option in the tool palette. Tiles with an enum value are outlined in the relevant colour, as defined in the tileset editor. Tiles with multiple enum values are indicated by nested outlines. 
I made this change because I was finding it difficult to determine if tiles had enum set correctly. See #698. Also, this is my first encounter with a Haxe project so I could have taken the wrong approach with this, and there could be unforeseen issues that I've not though of.
Summary of changes:
* Adds a new "Tile enums" item to the editing options
* Adds a new `tileEnumOverlays` boolean setting
* Adds `TilesetEnumChanged` event, triggered when an …
=> Tileset enum overlay

src/electron.renderer/ui/modal/panel/EditAllAutoLayerRules.hx
For real this time, without unintended commits. Renames faulty variable references while still providing the intended fix.
=> Fix build failure stemming from #738

app/package.json
Currently, the macOS build is Intel-only, which runs less than optimal on Apple Silicon due to it running through the [Rosetta 2 translation layer](https://support.apple.com/en-us/HT211861).
This PR adds the `--universal` flag which instructs `electron-builder` to generate a binary that contains code for both macOS architectures.
Worth noting that this technique does increase the size of the macOS app by approximately 80% (from ~215MB to ~390MB), but keeps the package script simple, not having to set up separate build steps for each etc.
=> Build universal binary for macOS supporting both Intel and Apple Silicon

app/assets/css/app.scss, docs/CHANGELOG.md
Fixed the Assitant resizing as you pan around and zoom.
I think the assistant being mostly fullscreen all the time makes sense makes it easier to select the tiles.
=> Fix assistant resizing as you pan

src/electron.renderer/ui/Modal.hx
Closes #826. 
This PR basically changes the way `closeAll()` in `Modal.hx` works. Instead of looping through all the open modals and closing them, it does the same thing but instead it loops through `ALL` in reverse.
=> Fix crashing when pressing Shift+W in rule editor

app/package.json
This makes the generated Rust types a little easier to use in real projects.
=> Automatically derive Clone and Debug in generated Rust types, make fields public

src/electron.renderer/exporter/Tiled.hx
PR for issue I created earlier today - https://github.com/deepnight/ldtk/issues/988#issue-1962690981
These changes will only add custom properties for root-level JSON key/value pairs for each tile in the tileset that has custom data defined. It will ignore plain text custom data or object/array values if the custom data is a JSON. The properties will be added with their name, respective type of `bool`, `string`, `int`, or `float`, and value. The `string` type does not add the type qualifier to the property element as this was the behavior I observed when saving custom properties directly in Tiled.
This is my first time writing any Haxe so please go easy on me!
=> Persist tile custom data to Tiled custom properties

app/assets/tpl/editLayerDefs.html, src/electron.renderer/Tool.hx, src/electron.renderer/data/def/LayerDef.hx, src/electron.renderer/display/LevelRender.hx, src/electron.renderer/ui/modal/panel/EditLayerDefs.hx
Adds an option for a custom guide grid color to layers. This PR depends on [deepnight/ldtk-haxe-api#39](https://github.com/deepnight/ldtk-haxe-api/pull/39)
=> Custom Guide Grid Color

app/assets/tpl/fieldDefsForm.html, app/assets/tpl/pages/editor.html
Small PR that fixes the issues below. Notably involved moving the class name `F_String` from the tooltip used by numerical properties to the tooltip used by Text properties.
=> fix spelling error, change default value tooltip for strings
